### PR TITLE
'device_state_attributes' is now deprecated

### PR DESCRIPTION
**Pull request by mjoshd**
'device_state_attributes' is deprecated starting with HA 2021.12.0
replaced 'device_state_attributes' with 'extra_state_attributes'

### CODE REVIEW

**Comment by dexsta** [comment]
@mjoshd excuse my dumbness. Does one need to change the code for this manually?



>

**Comment by skilau** [comment]
> @mjoshd excuse my dumbness. Does one need to change the code for this manually?
> 
> >

Until this patch is accepted and a new version is released, yes.

Either that, or you can fork it, and make the change, and have HACS pull from your repo instead.

Since this driver is mostly (all?) abandoned, it might make sense to fork it yourself...

I know for myself, I intend to use this driver until my 2 USB dongles die, as the driver works extremely well, for what it is/does.
So I have forked it, and have HA/HACS pulling my fork.

**Comment by stanwebber** [comment]
create your own fork or use hacs to pull from an existing fork that someone else is already keeping up to date. erlanger's or mine are good ones. probably skilau's too, but i haven't looked at it.

**Comment by benderunit22** [comment]
> @mjoshd excuse my dumbness. Does one need to change the code for this manually?
> 
> >Forgive my ignorance.  How did you resolve this issue?  Did you just edit the binary_sensor.py file or did you go with the fork?  Do you have to rescan all your sensors again after making the change in either case?

**Pull request merged**
