### PR TITLE
Remove scan of dongle for paired sensors

### LINKED ISSUE #29: TimeoutError: _DoCommand
Trying to get this to work on my Raspberrypi 3B+, but getting Timeout Error: _DoCommand during startup. The dongle status light is blue, so I believed it is has been recognized, but still getting timeout. Currently running Hassio v0.98.5.
====================================
2019-09-11 21:35:43 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-09-11 21:35:44 INFO (MainThread) [homeassistant.setup] Setup of domain logger took 0.0 seconds.
2019-09-11 21:35:45 INFO (MainThread) [homeassistant.setup] Setting up http
2019-09-11 21:35:45 INFO (MainThread) [homeassistant.setup] Setup of domain http took 0.0 seconds.
2019-09-11 21:35:45 INFO (MainThread) [homeassistant.setup] Setting up system_log
2019-09-11 21:35:45 INFO (MainThread) [homeassistant.setup] Setup of domain system_log took 0.0 seconds.
2019-09-11 21:35:45 INFO (MainThread) [homeassistant.setup] Setting up recorder
2019-09-11 21:35:47 WARNING (Recorder) [homeassistant.components.recorder] Ended unfinished session (id=9 from 2019-09-12 01:20:00.915227)
2019-09-11 21:35:48 INFO (MainThread) [homeassistant.setup] Setup of domain recorder took 2.7 seconds.
2019-09-11 21:35:48 INFO (MainThread) [homeassistant.setup] Setting up updater
2019-09-11 21:35:48 INFO (MainThread) [homeassistant.setup] Setup of domain updater took 0.0 seconds.
2019-09-11 21:35:50 INFO (MainThread) [homeassistant.setup] Setting up ssdp
2019-09-11 21:35:50 INFO (MainThread) [homeassistant.setup] Setup of domain ssdp took 0.0 seconds.
2019-09-11 21:35:51 INFO (SyncWorker_19) [homeassistant.util.package] Attempting install of aiofiles==0.4.0
2019-09-11 21:35:51 INFO (MainThread) [homeassistant.setup] Setting up sun
2019-09-11 21:35:51 INFO (MainThread) [homeassistant.setup] Setup of domain sun took 0.2 seconds.
2019-09-11 21:35:52 INFO (MainThread) [homeassistant.setup] Setting up person
2019-09-11 21:35:52 INFO (MainThread) [homeassistant.setup] Setting up lovelace
2019-09-11 21:35:52 INFO (MainThread) [homeassistant.setup] Setup of domain lovelace took 0.0 seconds.
2019-09-11 21:35:52 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for wyzesense which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-09-11 21:35:52 INFO (MainThread) [homeassistant.setup] Setting up group
2019-09-11 21:35:52 INFO (MainThread) [homeassistant.setup] Setup of domain group took 0.0 seconds.
2019-09-11 21:35:54 INFO (MainThread) [homeassistant.setup] Setting up api
2019-09-11 21:35:54 INFO (MainThread) [homeassistant.setup] Setting up system_health
2019-09-11 21:35:54 INFO (MainThread) [homeassistant.setup] Setup of domain system_health took 0.0 seconds.
2019-09-11 21:35:54 INFO (MainThread) [homeassistant.setup] Setting up auth
2019-09-11 21:35:54 INFO (MainThread) [homeassistant.setup] Setup of domain auth took 0.0 seconds.
2019-09-11 21:35:54 INFO (MainThread) [homeassistant.setup] Setting up webhook
2019-09-11 21:35:54 INFO (MainThread) [homeassistant.setup] Setup of domain webhook took 0.0 seconds.
2019-09-11 21:35:55 INFO (MainThread) [homeassistant.setup] Setting up script
2019-09-11 21:35:55 INFO (MainThread) [homeassistant.setup] Setup of domain script took 0.0 seconds.
2019-09-11 21:35:55 INFO (MainThread) [homeassistant.setup] Setting up config
2019-09-11 21:35:55 INFO (MainThread) [homeassistant.setup] Setting up websocket_api
2019-09-11 21:35:55 INFO (MainThread) [homeassistant.setup] Setup of domain websocket_api took 0.0 seconds.
2019-09-11 21:35:55 INFO (MainThread) [homeassistant.setup] Setting up history
2019-09-11 21:35:55 INFO (MainThread) [homeassistant.setup] Setup of domain history took 0.0 seconds.
2019-09-11 21:35:55 INFO (MainThread) [homeassistant.setup] Setup of domain api took 0.4 seconds.
2019-09-11 21:35:55 INFO (MainThread) [homeassistant.setup] Setting up onboarding
2019-09-11 21:35:55 INFO (MainThread) [homeassistant.setup] Setting up automation
2019-09-11 21:35:55 INFO (MainThread) [homeassistant.setup] Setup of domain automation took 0.0 seconds.
2019-09-11 21:35:55 INFO (MainThread) [homeassistant.setup] Setup of domain config took 0.2 seconds.
2019-09-11 21:35:55 INFO (MainThread) [homeassistant.setup] Setup of domain onboarding took 0.2 seconds.
2019-09-11 21:35:55 INFO (MainThread) [homeassistant.setup] Setup of domain person took 3.4 seconds.
2019-09-11 21:37:09 INFO (SyncWorker_14) [homeassistant.util.package] Attempting install of aiogithubapi==0.2.0
2019-09-11 21:38:43 INFO (SyncWorker_5) [homeassistant.util.package] Attempting install of integrationhelper==0.2.2
2019-09-11 21:40:16 INFO (MainThread) [homeassistant.setup] Setting up hacs
2019-09-11 21:40:16 INFO (MainThread) [hacs] 
-------------------------------------------------------------------
HACS (Home Assistant Community Store)

Version: 0.13.2
This is a custom integration
If you have any issues with this you need to open an issue here:
https://github.com/custom-components/hacs/issues
-------------------------------------------------------------------

2019-09-11 21:40:17 INFO (MainThread) [homeassistant.setup] Setting up met
2019-09-11 21:40:17 INFO (MainThread) [homeassistant.setup] Setup of domain met took 0.0 seconds.
2019-09-11 21:40:17 INFO (SyncWorker_13) [homeassistant.util.package] Attempting install of wyzesense==0.0.4
2019-09-11 21:40:17 INFO (SyncWorker_6) [homeassistant.loader] Loaded weather from homeassistant.components.weather
2019-09-11 21:40:17 INFO (MainThread) [homeassistant.setup] Setting up weather
2019-09-11 21:40:17 INFO (MainThread) [homeassistant.setup] Setup of domain weather took 0.0 seconds.
2019-09-11 21:40:17 INFO (MainThread) [homeassistant.components.weather] Setting up weather.met
2019-09-11 21:40:22 INFO (MainThread) [hacs.repository.integration.custom-components.hacs] Registration complete
2019-09-11 21:40:22 INFO (MainThread) [hacs.data] Restore started
2019-09-11 21:40:22 INFO (MainThread) [hacs.data] Restore done
2019-09-11 21:40:22 INFO (MainThread) [homeassistant.setup] Setup of domain hacs took 5.8 seconds.
2019-09-11 21:40:22 INFO (SyncWorker_16) [homeassistant.loader] Loaded sensor from homeassistant.components.sensor
2019-09-11 21:40:22 INFO (MainThread) [homeassistant.setup] Setting up sensor
2019-09-11 21:40:22 INFO (MainThread) [homeassistant.setup] Setup of domain sensor took 0.0 seconds.
2019-09-11 21:40:22 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.hacs
2019-09-11 21:41:56 INFO (SyncWorker_10) [homeassistant.util.package] Attempting install of retry==0.9.2
2019-09-11 21:43:07 INFO (MainThread) [homeassistant.setup] Setting up binary_sensor
2019-09-11 21:43:07 INFO (SyncWorker_9) [homeassistant.loader] Loaded google_translate from homeassistant.components.google_translate
2019-09-11 21:43:09 INFO (MainThread) [homeassistant.setup] Setting up mobile_app
2019-09-11 21:43:10 INFO (MainThread) [homeassistant.setup] Setting up cloud
2019-09-11 21:43:13 INFO (MainThread) [homeassistant.setup] Setting up zeroconf
2019-09-11 21:43:13 INFO (MainThread) [homeassistant.setup] Setting up frontend
2019-09-11 21:43:13 INFO (MainThread) [homeassistant.setup] Setup of domain frontend took 0.1 seconds.
2019-09-11 21:43:13 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.wyzesense
2019-09-11 21:43:13 INFO (MainThread) [homeassistant.setup] Setup of domain mobile_app took 4.1 seconds.
2019-09-11 21:43:13 DEBUG (SyncWorker_5) [custom_components.wyzesense.binary_sensor] WYZESENSE v0.0.4
2019-09-11 21:43:13 DEBUG (SyncWorker_5) [custom_components.wyzesense.binary_sensor] Attempting to open connection to hub at /dev/hidraw0
2019-09-11 21:43:13 DEBUG (SyncWorker_5) [custom_components.wyzesense.wyzesense_custom] Start Inquiry...
2019-09-11 21:43:13 DEBUG (SyncWorker_5) [custom_components.wyzesense.wyzesense_custom] ===> Sending: Packet: Cmd=4327, Payload=<None>
2019-09-11 21:43:13 DEBUG (SyncWorker_5) [custom_components.wyzesense.wyzesense_custom] Sending: b'aa55430327016c'
2019-09-11 21:43:13 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] Trying to parse: b'55aa43042801016f'
2019-09-11 21:43:13 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] Received: b'55aa43042801016f'
2019-09-11 21:43:13 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] <=== Received: Packet: Cmd=4328, Payload=b'01'
2019-09-11 21:43:14 DEBUG (SyncWorker_5) [custom_components.wyzesense.wyzesense_custom] Inquiry returns 1
2019-09-11 21:43:14 DEBUG (SyncWorker_5) [custom_components.wyzesense.wyzesense_custom] ===> Sending: Packet: Cmd=5314, Payload=b'ff'
2019-09-11 21:43:14 DEBUG (SyncWorker_5) [custom_components.wyzesense.wyzesense_custom] Sending: b'aa55530414ff0269'
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] Trying to parse: b'55aa5314ff026555aa530e3500000000000000000314ff02ab55aa530315016a'
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] Received: b'55aa5314ff0265'
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] <=== Received: Packet: Cmd=53FF, Payload=ACK(5314)
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] Trying to parse: b'55aa530e3500000000000000000314ff02ab55aa530315016a55aa530315016a'
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] Received: b'55aa530e3500000000000000000314ff02ab'
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] <=== Received: Packet: Cmd=5335, Payload=b'00000000000000000314ff'
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] ===> Sending: Packet: Cmd=53FF, Payload=ACK(5335)
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] Sending: b'aa555335ff0286'
2019-09-11 21:43:14 INFO (Thread-2) [custom_components.wyzesense.wyzesense_custom] LOG: time=1969-12-31T19:00:00, data=b'14ff'
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] Trying to parse: b'55aa530315016a55aa530315016a'
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] Received: b'55aa530315016a'
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] <=== Received: Packet: Cmd=5315, Payload=<None>
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] ===> Sending: Packet: Cmd=53FF, Payload=ACK(5315)
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] Sending: b'aa555315ff0266'
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] Trying to parse: b'55aa530315016a'
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] Received: b'55aa530315016a'
2019-09-11 21:43:14 DEBUG (SyncWorker_5) [custom_components.wyzesense.wyzesense_custom] Start GetSensors...
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] <=== Received: Packet: Cmd=5315, Payload=<None>
2019-09-11 21:43:14 DEBUG (SyncWorker_5) [custom_components.wyzesense.wyzesense_custom] ===> Sending: Packet: Cmd=532E, Payload=<None>
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] ===> Sending: Packet: Cmd=53FF, Payload=ACK(5315)
2019-09-11 21:43:14 DEBUG (SyncWorker_5) [custom_components.wyzesense.wyzesense_custom] Sending: b'aa5553032e0183'
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] Sending: b'aa555315ff0266'
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] Trying to parse: b'55aa5303320187'
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] Received: b'55aa5303320187'
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] <=== Received: Packet: Cmd=5332, Payload=<None>
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] ===> Sending: Packet: Cmd=53FF, Payload=ACK(5332)
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] Sending: b'aa555332ff0283'
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] ===> Sending: Packet: Cmd=5333, Payload=b'0000016d2323892f'
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] Sending: b'aa55530b330000016d2323892f02fc'
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] Trying to parse: b'55aa532eff027f55aa53042f020187'
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] Received: b'55aa532eff027f'
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] <=== Received: Packet: Cmd=53FF, Payload=ACK(532E)
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] Trying to parse: b'55aa53042f02018755aa5303320187'
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] Received: b'55aa53042f020187'
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] <=== Received: Packet: Cmd=532F, Payload=b'02'
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] ===> Sending: Packet: Cmd=53FF, Payload=ACK(532F)
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] Sending: b'aa55532fff0280'
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] Trying to parse: b'55aa530332018755aa5333ff0284'
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] Received: b'55aa5303320187'
2019-09-11 21:43:14 DEBUG (SyncWorker_5) [custom_components.wyzesense.wyzesense_custom] 2 sensors reported, waiting for each one to report...
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] <=== Received: Packet: Cmd=5332, Payload=<None>
2019-09-11 21:43:14 DEBUG (SyncWorker_5) [custom_components.wyzesense.wyzesense_custom] ===> Sending: Packet: Cmd=5330, Payload=b'02'
2019-09-11 21:43:14 INFO (MainThread) [homeassistant.setup] Setting up tts
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] ===> Sending: Packet: Cmd=53FF, Payload=ACK(5332)
2019-09-11 21:43:14 DEBUG (SyncWorker_5) [custom_components.wyzesense.wyzesense_custom] Sending: b'aa55530430020188'
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] Sending: b'aa555332ff0283'
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] ===> Sending: Packet: Cmd=5333, Payload=b'0000016d232389a4'
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] Sending: b'aa55530b330000016d232389a40371'
2019-09-11 21:43:14 INFO (MainThread) [homeassistant.setup] Setting up map
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] Trying to parse: b'55aa5333ff0284'
2019-09-11 21:43:14 INFO (MainThread) [homeassistant.setup] Setup of domain map took 0.0 seconds.
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] Received: b'55aa5333ff0284'
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] <=== Received: Packet: Cmd=53FF, Payload=ACK(5333)
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] Trying to parse: b'55aa5330ff028155aa530b3137373837383139450352'
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] Received: b'55aa5330ff0281'
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] <=== Received: Packet: Cmd=53FF, Payload=ACK(5330)
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] Trying to parse: b'55aa530b3137373837383139450352'
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] Received: b'55aa530b3137373837383139450352'
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] <=== Received: Packet: Cmd=5331, Payload=b'3737383738313945'
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] ===> Sending: Packet: Cmd=53FF, Payload=ACK(5331)
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] Sending: b'aa555331ff0282'
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] Sensor 1/2, MAC:7787819E
2019-09-11 21:43:14 INFO (MainThread) [homeassistant.setup] Setting up logbook
2019-09-11 21:43:14 INFO (MainThread) [homeassistant.setup] Setup of domain logbook took 0.0 seconds.
2019-09-11 21:43:14 INFO (MainThread) [homeassistant.setup] Setting up panel_custom
2019-09-11 21:43:14 INFO (MainThread) [homeassistant.setup] Setup of domain panel_custom took 0.0 seconds.
2019-09-11 21:43:14 INFO (MainThread) [homeassistant.setup] Setup of domain zeroconf took 1.6 seconds.
2019-09-11 21:43:14 INFO (SyncWorker_8) [homeassistant.loader] Loaded notify from homeassistant.components.notify
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] Trying to parse: b'55aa5333ff0284'
2019-09-11 21:43:14 INFO (SyncWorker_6) [homeassistant.loader] Loaded esphome from homeassistant.components.esphome
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] Received: b'55aa5333ff0284'
2019-09-11 21:43:14 DEBUG (Thread-2) [custom_components.wyzesense.wyzesense_custom] <=== Received: Packet: Cmd=53FF, Payload=ACK(5333)
2019-09-11 21:43:14 INFO (MainThread) [homeassistant.setup] Setting up hassio
2019-09-11 21:43:14 INFO (MainThread) [homeassistant.setup] Setting up notify
2019-09-11 21:43:14 INFO (MainThread) [homeassistant.setup] Setup of domain notify took 0.0 seconds.
2019-09-11 21:43:16 INFO (MainThread) [homeassistant.components.notify] Setting up notify.mobile_app
2019-09-11 21:43:16 INFO (MainThread) [homeassistant.setup] Setup of domain cloud took 6.7 seconds.
2019-09-11 21:43:16 INFO (MainThread) [homeassistant.setup] Setup of domain tts took 2.2 seconds.
2019-09-11 21:43:18 INFO (MainThread) [homeassistant.setup] Setting up default_config
2019-09-11 21:43:18 INFO (SyncWorker_16) [homeassistant.loader] Loaded stream from homeassistant.components.stream
2019-09-11 21:43:18 INFO (SyncWorker_12) [homeassistant.loader] Loaded homekit_controller from homeassistant.components.homekit_controller
2019-09-11 21:43:18 INFO (MainThread) [homeassistant.setup] Setting up stream
2019-09-11 21:43:18 INFO (MainThread) [homeassistant.setup] Setup of domain stream took 0.0 seconds.
2019-09-11 21:43:18 INFO (MainThread) [homeassistant.setup] Setup of domain default_config took 0.2 seconds.
2019-09-11 21:43:19 INFO (MainThread) [homeassistant.setup] Setup of domain hassio took 4.7 seconds.
2019-09-11 21:43:23 WARNING (MainThread) [homeassistant.components.binary_sensor] Setup of platform wyzesense is taking over 10 seconds.
2019-09-11 21:43:24 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up platform wyzesense
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/wyzesense/binary_sensor.py", line 85, in setup_platform
    result = ws.List()
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 507, in List
    sensors = self._GetSensors()
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 479, in _GetSensors
    self._DoCommand(Packet.GetSensorList(count), cmd_handler, timeout=self._CMD_TIMEOUT * count)
  File "/config/custom_components/wyzesense/wyzesense_custom.py", line 384, in _DoCommand
    raise TimeoutError("_DoCommand")
TimeoutError: _DoCommand
2019-09-11 21:43:24 INFO (MainThread) [homeassistant.setup] Setup of domain binary_sensor took 17.4 seconds.
2019-09-11 21:43:24 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.updater
2019-09-11 21:43:24 INFO (MainThread) [homeassistant.bootstrap] Home Assistant initialized in 462.37s
2019-09-11 21:43:24 INFO (MainThread) [homeassistant.core] Starting Home Assistant
2019-09-11 21:43:24 INFO (MainThread) [hacs] Loading known repositories
2019-09-11 21:43:24 INFO (MainThread) [homeassistant.core] Timer:starting
2019-09-11 21:48:20 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 275, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp\_http_parser.pyx", line 523, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: invalid HTTP method

### PR DESCRIPTION
**Pull request by photinus**
Stores the sensors in a local file instead of relying on the dongle to return paired sensors. Resolved 
Fixes #29

### CODE REVIEW

**Comment by shauder** [comment]
I don't think you actually need to write them to a file and read from the file. The error check for mac size should be enough right?

**Comment by photinus** [comment]
So, I'm writing the macs out to the file to allow for the entity setup on initialization of the platform. Otherwise it will pick them up as they check in, but at least in my use case I want them to always show up. If I dont set them up at initialization I end up with error icons in my front end till they check in for the first time.

**Comment by kevinvincent** [comment]
WIll test your contribution this weekend and push it out! Thank you!

**Comment by photinus** [comment]
Any chance we can merge this change in? I've had a few people message me about the issue popping up for them.

**Comment by photinus** [comment]
Would you be interested/willing to add me as a maintainer of the repo so I can help keep this updated and push forward with development? I'm happy to help and keep things moving.

**Comment by kevinvincent** [comment]
Hi @photinus 
Sorry I've been insanely busy these last few months trying to graduate from my undergrad. I'd definitely be willing to add you as a maintainer. Please look out for the email from github. Sorry about the lack of response.

Thank you.

**Comment by kevinvincent** [comment]
@photinus Will this result in devices disappearing on restart until they are triggered for the first time? I assume this will happen when upgrading to this version?

**Comment by kevinvincent** [comment]
Basically the README says this:

> * Restart HA and the sensors you have already bound to the hub (using the wyze app for example) will show up in your entities as `off` with `assumed_state: true` and no `device_class`. These will update and other attributes will be added once the component hears from the sensor for the first time.

But that is now wrong as the sensors will only show up once it triggers for the first time right? I can update the README if you confirm this.

**Pull request merged**
